# Generated by Django 3.1.3 on 2020-11-18 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('update_by_time_stamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='poster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieposter_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieposter_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('update_by_time_stamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movieposter')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
