# Generated by Django 3.1.3 on 2020-11-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_path',
            field=models.FileField(default='xy', upload_to='Movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieposter',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movieposter',
            name='bg_type',
            field=models.CharField(choices=[('master', 'master'), ('slave', 'slave')], default='img', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieposter',
            name='header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movieposter',
            name='sub_header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
